# Change these first
owner: michelangelobottura # Your GitHub organization or username, where this repository lives
repo: ctaoit-upptime # The name of this repository

sites:
  - name: www.cta-observatory.org 
    url: https://www.cta-observatory.org
  - name: indico.cta-observatory.org 
    url: https://indico.cta-observatory.org
  - name: redmine.cta-observatory.org
    url: https://redmine.cta-observatory.org
  - name: gitlab.cta-observatory.org
    url: https://gitlab.cta-observatory.org
  - name: git.cta-observatory.org
    url: https://git.cta-observatory.org
  - name: jama.cta-observatory.org
    url: https://jama.cta-observatory.org
  - name: RAMS license server
    check: "tcp-ping"
    url: reliasoft.cta-observatory.org
    port: 6220

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.cta-observatory.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ctaoit-upptime
  introTitle: "Status dashboard for CTAO applications"
  introMessage: Monitoring system entirely powered by Github. Set up by ctao-it (at) cta-observatory.org
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

