# Change these first
owner: michelangelobottura # Your GitHub organization or username, where this repository lives
repo: ctaoit-upptime # The name of this repository

sites:
  - name: www 
    url: https://www.cta-observatory.org
  - name: Indico 
    url: https://indico.cta-observatory.org
  - name: Redmine @DESY
    url: https://redmine.cta-observatory.org
  - name: Computing Gitlab @DESY
    url: https://gitlab.cta-observatory.org
  - name: CTAO IT Git
    url: https://git.cta-observatory.org
  - name: Jama
    url: https://jama.cta-observatory.org
  - name: Jama 8800
    check: "tcp-ping"
    url: jama.cta-observatory.org
    port: 8800

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.cta-observatory.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ctaoit-upptime
  introTitle: "Status dashboard for CTAO applications"
  introMessage: Monitoring system entirely powered by Github. Set up by ctao-it (at) cta-observatory.org
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

